#!/bin/bash

set -e
  
echo "[+] Adding supporting packages..."
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl

echo "[+] Adding caddy keys to package index"
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
chmod o+r /usr/share/keyrings/caddy-stable-archive-keyring.gpg 
chmod o+r /etc/apt/sources.list.d/caddy-stable.list 

echo "[+] Updating packages and installing caddy"
sudo apt update
sudo apt install caddy
